// App.tsx (paste into src/App.tsx)
"use client";

import React, { useEffect, useState, useCallback } from "react";
import { AnimatePresence } from "framer-motion";
import { Toaster, toast } from "sonner";
import { Box } from "lucide-react";

import { DashboardLayout } from "./components/DashboardLayout";
import { DualPanelView } from "./components/DualPanelView";
import { MachineGallery } from "./components/MachineGallery";
import { MachineCanvas } from "./components/MachineCanvas";
import { AuthModal } from "./components/AuthModal";
import { CyberpunkBackground } from "./components/CyberpunkBackground";
import SettingSection  from "./components/SettingSection";
import ChatInterface from "./components/ChatInterface";

import  AIEnvironmentProvider  from "./context/AIEnvironmentContext";

type Views = "home" | "chat" | "models" | "3d-view" | "settings";

interface MachineData {
  type: "robot" | "drone";
  name: string;
  description: string;
  specifications: string[];
  assembly: string[];
}

function BootScreen() {
  return (
    <div className="absolute inset-0 flex flex-col items-center justify-center bg-black/95 text-cyan-300 font-mono text-sm z-50">
      <p className="animate-pulse">Booting Virtual Factory Core...</p>
      <div className="bg-gray-900/60 border border-cyan-500/20 rounded-md p-2 text-xs mt-4">
        <p>&gt; Loading AI Modules</p>
        <p>&gt; Connecting Neural Mesh</p>
        <p>&gt; Systems Online</p>
      </div>
    </div>
  );
}

export default function App() {
  const [activeView, setActiveView] = useState<Views>("chat");
  const [isBooting, setIsBooting] = useState(true);
  const [isAuthenticated, setIsAuthenticated] = useState(false);
  const [showAuthModal, setShowAuthModal] = useState(false);

  const [machineData, setMachineData] = useState<MachineData | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  useEffect(() => {
    document.documentElement.classList.add("dark");
    const t = setTimeout(() => setIsBooting(false), 1200);
    return () => clearTimeout(t);
  }, []);

  useEffect(() => {
    const val = localStorage.getItem("virtualFactoryAuth");
    if (val === "true") setIsAuthenticated(true);
    else setShowAuthModal(true);
  }, []);

  const handleLogin = useCallback((email: string) => {
    localStorage.setItem("virtualFactoryAuth", "true");
    localStorage.setItem("virtualFactoryUser", email);
    setIsAuthenticated(true);
    setShowAuthModal(false);
    toast.success("Welcome back!");
  }, []);

  const generateMachine = useCallback((query: string) => {
    setIsGenerating(true);
    const lower = query.toLowerCase();
    const isDrone = lower.includes("drone");

    const mock: MachineData = isDrone
      ? {
          type: "drone",
          name: "AI Drone",
          description: "Autonomous drone generated by AI.",
          specifications: ["30 min flight", "4K camera"],
          assembly: ["Attach motors", "Connect controller"],
        }
      : {
          type: "robot",
          name: "Robotic Arm",
          description: "6-axis industrial robotic arm.",
          specifications: ["10kg payload", "±0.05mm"],
          assembly: ["Mount base", "Attach joints"],
        };

    setTimeout(() => {
      setMachineData(mock);
      setIsGenerating(false);
      toast.success("Machine Generated!");
    }, 1500);
  }, []);

  const renderView = () => {
    switch (activeView) {
      case "chat":
        return <ChatInterface backendUrl="https://backend1-4-kx23.onrender.com" />;
      case "models":
        return <MachineGallery onSelectExample={generateMachine} />;
      case "3d-view":
        return machineData ? (
          <MachineCanvas machineType={machineData.type} isLoading={isGenerating} />
        ) : (
          <div className="flex flex-col h-full items-center justify-center text-gray-300">
            <Box className="w-16 h-16 text-cyan-400 mb-4" />
            Generate a machine first
          </div>
        );
      case "settings":
        return <SettingSection />;
      default:
        return <DualPanelView isGenerating={isGenerating} onGenerate={generateMachine} machineData={machineData} />;
    }
  };

  if (!isAuthenticated) {
    return (
      <AIEnvironmentProvider>
        <div className="min-h-screen bg-background relative overflow-hidden">
          <CyberpunkBackground />
          <AnimatePresence>{isBooting && <BootScreen />}</AnimatePresence>
          <AuthModal isOpen={showAuthModal} onClose={() => {}} onLogin={handleLogin} />
        </div>
        <Toaster position="bottom-right" />
      </AIEnvironmentProvider>
    );
  }

  return (
    <AIEnvironmentProvider>
      <div className="h-screen w-screen bg-background text-white relative overflow-hidden">
        <CyberpunkBackground />
        <AnimatePresence>{isBooting && <BootScreen />}</AnimatePresence>

        <DashboardLayout
          activeView={activeView}
          onViewChange={setActiveView}
          onSearch={generateMachine}
          onLogout={() => {
            localStorage.removeItem("virtualFactoryAuth");
            setIsAuthenticated(false);
            setShowAuthModal(true);
          }}
          ollamaConnected={true}
          modelName="Perplexity"
        >
          {renderView()}
        </DashboardLayout>

        <Toaster position="bottom-right" />
      </div>
    </AIEnvironmentProvider>
  );
}

